fix for apiVersion not being set when updating status
IBM/oper8 pull request #87
Opened 2024-07-02 19:41 UTC by pit1sIBM

## Related Issue
Supports https://github.com/IBM/oper8/issues/72

## Related PRs
This PR is not dependent on any other PR

## What this PR does / why we need it
When `_update_resource_status` is called, we're pulling api version from the wrong field so it's set to `None`. This causes issues when multiple Kinds exist that share a name. 

Patched locally you can see the difference
```
2024-07-02T19:10:52.079619 [RECON:INFO:46915769992768] Reconciling resource WatsonDiscoveryCNM/zen/wd
2024-07-02T19:10:52.080065 [DEBUG:WARN:46915769992768] ===== updating resource status with patch ======
2024-07-02T19:10:52.080644 [DEBUG:WARN:46915199272512] OLD: None/WatsonDiscoveryCNM/wd
2024-07-02T19:10:52.080847 [DEBUG:WARN:46915769992768] NEW: discovery.watson.ibm.com/v1/WatsonDiscoveryCNM/wd
2024-07-02T19:10:52.081029 [DEBUG:WARN:46915769992768] ===== updating resource status with patch ======
```

## Special notes for your reviewer

## If applicable**
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

## What gif most accurately describes how I feel towards this PR?
![Example of a gif](https://media1.tenor.com/m/KRS1qz0uobkAAAAd/pulp-fiction-john-travolta.gif)

2024-07-02 19:43 UTC, gabe-l-hart requested changes
Yikes, good catch! Can you throw in a unit test for this?

2024-07-02 20:49 UTC, pit1sIBM commented
I can do that, though I'm unsure how to start. Should I be testing `status.update_resource_status` since that's really doing the work here? Maybe adding some validation to the `reconcile._update_resource_status` to handle/error on a None apiVersion (since there should always be on present in the manifest)?

2024-07-02 20:52 UTC, gabe-l-hart commented
Ah! Actually, I was moving quickly and missed that the second file changed _was_ a unit test. Maybe just add an `assert manifest.apiVersion == "some real string"`. The `api_version` vs `apiVersion` thing has bitten us before, so it's good to make sure that it's not falling back to the default `None` just because `manifest` is an `aconfig.Config`.

2024-07-02 21:35 UTC, pit1sIBM commented
Just to be sure, this should be in `reconcile._update_resource_status`, right? Similar to what's done in ManagedObject?
https://github.com/IBM/oper8/blob/56260095e1a61946209d9b20989e3e80c43f9092/oper8/managed_object.py#L29-L30

So prior to calling status.update_resource_status, we check for apiVersion, kind, and name are set?

2024-07-02 21:47 UTC, gabe-l-hart commented
It won't let me make a `suggestion` over lines that aren't changed in the PR, but here's what I'm thinking:

```py
def test_update_resource_status():
    """Test updating resource status"""
    dm = MockDeployManager()
    the_api_version = "my.api/v123alpha0"
    cr = setup_cr(api_version=the_api_version)
    rm = ReconcileManager(deploy_manager=dm)
    with mock.patch("oper8.status.update_resource_status") as Mock:
        rm._update_resource_status(dm, cr, current_status={"test": "status"})
        Mock.assert_called_with(
            dm,
            cr.kind,
            the_api_version,
            cr.metadata.name,
            cr.metadata.namespace,
            current_status={"test": "status"},
        )
```

2024-07-03 02:26 UTC, pit1sIBM commented
Gotcha, I saw setup_cr defaults to  `foo.bar.com/v123` and was trying to sort out how to verify that but that makes more sense 😄  Much appreciated @gabe-l-hart! I've included the change

2024-07-03 15:47 UTC, HonakerM approved these changes
LGTM! Thank you for implementing this

2024-07-03 15:48 UTC, gabe-l-hart approved these changes
Looks good!

2024-07-03 15:48 UTC, merged